### PR TITLE
US187198: Modified policy management APIs to support obligations

### PR DESCRIPTION
**Pull request by irinaepshteyn**

### CODE REVIEW

**Comment by sanjeevchopra** [comment]
* Lets hold-off on merging this until we have a CI loop setup on eclipse.
* Also, we may want to keep this in the branch until policy evaluation is also changed to match and return obligations. At least, there needs to be a clear indication to a developer when looking at the policy mgmt API, that obligations are not returned.

**Comment by sanjeevchopra** [comment]
If possible, please post summary documentation of this feature in the wiki section of this repo, as a proposal for community review/feedback.

**Comment by irinaepshteyn** [comment]
Changed the base to feature/obligations.  Will continue merging stories into this branch until feature is complete.  We should be able then merge complete implementation of obligations feature/obligations into master.

**Comment by irinaepshteyn** [comment]
Added wiki: https://github.com/eclipse/keti/wiki/Obligations-in-Keti

**Pull request merged**
